# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Custom', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pizzas',
                'verbose_name': 'Pizza',
            },
        ),
        migrations.CreateModel(
            name='PizzaToppingRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app_5.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Toppings',
                'verbose_name': 'Topping',
            },
        ),
        migrations.AddField(
            model_name='pizzatoppingrelationship',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app_5.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, through='example_app_5.PizzaToppingRelationship', to='example_app_5.Topping'),
        ),
    ]
